### ISSUE TITLE
make  `ISO` avaibalble again

### ISSUE THREAD

**Issue by OmiChrome** [Matiashik/neco-arch#1]
UUWUWUWUWUWWUWUW

uwuw

**Comment by LeonidPilyugin** [comment]
Hewwo ( ͡o ω ͡o )!
sowwy fow nyot answewing fow s-so wong (U ᵕ U❁)
you c-can downwoad iso fwom dwopbox. (⑅˘꒳˘) thewe awen't any p-pwobwems with it, a-awe they o.O?
Link: https://www.dropbox.com/scl/fi/xs91p9vcbwz6z4dxnhlsg/menheraos-04_02_2024-x86_64.iso

**Comment by LeonidPilyugin** [comment]
The actual link on latest build is always here
![screenshot_20240311_211449](https://github.com/LeonidPilyugin/menheraOS/assets/63973002/98ae4243-ee2e-4d6f-99b3-5877fc6a2339)

**Comment by OmiChrome** [comment]
it requires sign in ! 
i dont have account

**Comment by LeonidPilyugin** [comment]
We cweated a [rewease](https://github.com/LeonidPilyugin/menheraOS/releases/tag/uwu) with zipped i-iso file, nyah~

**Comment by LeonidPilyugin** [comment]
Awso i shawed fiwe in dwopbox. OwO you c-can wog in with g-googwe account a-and downwoad it

**Comment by OmiChrome** [comment]
i downt rike miwacosot so i wownt go faw it..
o_0

**Comment by LeonidPilyugin** [comment]
So, i think, the question is settwed an I c-can cwose the issue

UwU
