### ISSUE TITLE
Can't Install MenheraOS

### ISSUE THREAD

**Issue by LunaHoshigure** [Matiashik/neco-arch#2]
When i try to install MenheraOS i got error

Intallation failed
Bad unpackfs configuration

Details:
The source filesystem "/run/archiso/bootmnt/menheraos/x86_64/airootfs.sfs does not exist
![IMG_20241019_070433](https://github.com/user-attachments/assets/7973daee-5281-42af-9da7-5aad363281f1)

**Comment by LunaHoshigure** [comment]
But it's work on virtual machine

**Comment by LeonidPilyugin** [comment]
Hewwo! Couwld you please list directory `/run/archiso/bootmnt/menheraos/x86_64/` if it exists? If not, do thewe exist its parent directories?

**Comment by LeonidPilyugin** [comment]
Alwso it will be good if you find where `airootfs.sfs` is located

**Comment by LunaHoshigure** [comment]
I managed to fix it but this time it's has problem with pacman package manager
Error: failed to commit transaction (invalid or corrupted package (PGP signature)

**Comment by LeonidPilyugin** [comment]
This problem occurs during installation or in installed system?

**Comment by LeonidPilyugin** [comment]
You can solve this problem by replacing `[kawaii]` section in `/etc/pacman.conf` with
```
[kawaii]
SigLevel = Optional TrustAll
Server = https://raw.githubusercontent.com/LeonidPilyugin/kawaii-repo/main/x86_64/
```
This will prevent pacman from checking package signatures. I have reproduced this problem in VM and am going to fix it

**Comment by LeonidPilyugin** [comment]
By the way, how did you fix the unpackfs problem? One time my friend encountered this failure on his computer, but the same ISO build was installing on another machine properly

**Comment by LunaHoshigure** [comment]
I fix unpackfs problem by creating "bootmnt" folder in /run/archiso and then copy "menheraos" from iso to "bootmnt" folder

**Comment by LeonidPilyugin** [comment]
Could you try [new build](https://github.com/LeonidPilyugin/menheraOS/releases/tag/19-10-2024) OwO? I think, it will fix these problems

**Comment by LunaHoshigure** [comment]
I tested it, And it's working fine now

**Comment by LeonidPilyugin** [comment]
UwU
